# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powerdown < Formula
  desc "CLI interface to the EskomSePush API."
  homepage "https://github.com/richardwooding/powerdown"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/richardwooding/powerdown/releases/download/v1.0.3/powerdown_1.0.3_Darwin_arm64.tar.gz"
      sha256 "2cd0ff7ffceb477ec8f7a927d2b3cbb92250502449f694280b3ed852a2a56af0"

      def install
        bin.install "powerdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/powerdown/releases/download/v1.0.3/powerdown_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "c729f2d5a7fd31c1a22e072c94b02ca22934fa873f02f4168b61fc13a4620566"

      def install
        bin.install "powerdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/powerdown/releases/download/v1.0.3/powerdown_1.0.3_Linux_arm64.tar.gz"
      sha256 "38166b7710fbd70b82bdd09bf67fa3af5f77ec6e1b0cf2252f6d196dd601d3ca"

      def install
        bin.install "powerdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/powerdown/releases/download/v1.0.3/powerdown_1.0.3_Linux_x86_64.tar.gz"
      sha256 "e076a19068c30778d1f0d19a06312016bbe374f938a79b5b8442cc524ac07c3b"

      def install
        bin.install "powerdown"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
