# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powerdown < Formula
  desc "CLI interface to the EskomSePush API."
  homepage "https://github.com/richardwooding/powerdown"
  version "0.1.29"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/richardwooding/powerdown/releases/download/v0.1.29/powerdown_0.1.29_Darwin_arm64.tar.gz"
      sha256 "8f3ecec660b209dc1ce54f5e1224dbe93a4a4082bd5f140e22b87172d3325f96"

      def install
        bin.install "powerdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/powerdown/releases/download/v0.1.29/powerdown_0.1.29_Darwin_x86_64.tar.gz"
      sha256 "8659172b99e0f3be369b830c18d37c5e8925192e028560e99006215d026df088"

      def install
        bin.install "powerdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/powerdown/releases/download/v0.1.29/powerdown_0.1.29_Linux_arm64.tar.gz"
      sha256 "ff174358c503516ff0bd6339bc928c0bd9417d4c7b704184adabc5129d6ecfd9"

      def install
        bin.install "powerdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/powerdown/releases/download/v0.1.29/powerdown_0.1.29_Linux_x86_64.tar.gz"
      sha256 "b7309ed086ed4050038a3718b4ae8b50ca6d8d24b206ee953951962dcc6684aa"

      def install
        bin.install "powerdown"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
